"""Inicio

Revision ID: fe522d0ca5f7
Revises: 
Create Date: 2026-05-29 14:20:58.588849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe522d0ca5f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('nit', sa.Text(), nullable=True),
    sa.Column('contacto_principal', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('direccion_principal', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.Text(), nullable=True),
    sa.Column('es_convenio', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('transportadoras',
    sa.Column('id_transportadora', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo_integracion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_transportadora')
    )
    op.create_table('colaboradores',
    sa.Column('id_colaborador', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('documento', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.Text(), nullable=True),
    sa.Column('municipio', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_colaborador')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.Text(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.Text(), nullable=False),
    sa.Column('producto_principal', sa.Text(), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=True),
    sa.Column('fecha_entrega_general', sa.Date(), nullable=True),
    sa.Column('vendedora', sa.Text(), nullable=True),
    sa.Column('estado_produccion', sa.Text(), nullable=True),
    sa.Column('estado_despacho', sa.Text(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_table('despachos',
    sa.Column('id_despacho', sa.Integer(), nullable=False),
    sa.Column('numero_despacho', sa.Text(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('tipo_despacho', sa.Text(), nullable=True),
    sa.Column('fecha_despacho', sa.Date(), nullable=True),
    sa.Column('transportadora', sa.Text(), nullable=True),
    sa.Column('estado_despacho', sa.Text(), nullable=True),
    sa.Column('cantidad_despachada', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_despacho'),
    sa.UniqueConstraint('numero_despacho')
    )
    op.create_table('entregas',
    sa.Column('id_entrega', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_colaborador', sa.Integer(), nullable=True),
    sa.Column('destinatario', sa.Text(), nullable=True),
    sa.Column('empresa', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.Text(), nullable=True),
    sa.Column('municipio', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('producto', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('estado_entrega', sa.Text(), nullable=True),
    sa.Column('transportadora', sa.Text(), nullable=True),
    sa.Column('guia_alas', sa.Text(), nullable=True),
    sa.Column('link_simpliroute', sa.Text(), nullable=True),
    sa.Column('tracking_pibox', sa.Text(), nullable=True),
    sa.Column('token_tracking', sa.Text(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_colaborador'], ['colaboradores.id_colaborador'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_entrega')
    )
    op.create_table('pedido_items',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('despacho_entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_despacho', sa.Integer(), nullable=False),
    sa.Column('id_entrega', sa.Integer(), nullable=False),
    sa.Column('cantidad_despachada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_despacho'], ['despachos.id_despacho'], ),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Text(), nullable=True),
    sa.Column('destinatario', sa.Text(), nullable=True),
    sa.Column('asunto', sa.Text(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('estado_envio', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('remisiones',
    sa.Column('id_remision', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.Column('id_despacho', sa.Integer(), nullable=True),
    sa.Column('numero_remision', sa.Text(), nullable=False),
    sa.Column('tipo_remision', sa.Text(), nullable=True),
    sa.Column('ruta_pdf', sa.Text(), nullable=True),
    sa.Column('nombre_archivo', sa.Text(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_genero', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_despacho'], ['despachos.id_despacho'], ),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_remision'),
    sa.UniqueConstraint('numero_remision')
    )
    op.create_table('tracking_eventos',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.Column('id_despacho', sa.Integer(), nullable=True),
    sa.Column('estado_anterior', sa.Text(), nullable=True),
    sa.Column('estado_nuevo', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('origen', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_despacho'], ['despachos.id_despacho'], ),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_eventos')
    op.drop_table('remisiones')
    op.drop_table('notificaciones')
    op.drop_table('despacho_entregas')
    op.drop_table('pedido_items')
    op.drop_table('entregas')
    op.drop_table('despachos')
    op.drop_table('pedidos')
    op.drop_table('colaboradores')
    op.drop_table('transportadoras')
    op.drop_table('clientes')
    # ### end Alembic commands ###
